apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SiadA2/Production-Grade-EKS-App.git
    targetRevision: HEAD
    path: helm-charts/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true